# Generated by Django 5.1.1 on 2024-09-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentredData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=55, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=55, null=True)),
                ('position', models.CharField(blank=True, max_length=55, null=True)),
                ('contact', models.CharField(blank=True, max_length=55, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_type', models.CharField(choices=[('volume', 'Volume customer'), ('retail', 'Retail customer')], default='retail', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, max_length=35, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=35, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('categories_supplied', models.CharField(blank=True, max_length=45, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=45, null=True)),
                ('product_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('interaction_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('feedback', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=55, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('nextdate', models.DateField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('number', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('worker', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('leadsrc', models.CharField(blank=True, max_length=55, null=True)),
                ('sector', models.CharField(blank=True, max_length=55, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('closed', 'Closed')], max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.centreddata')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('variant_value', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.PositiveIntegerField()),
                ('raison_retour', models.CharField(choices=[('defaut', 'Défaut de fabrication'), ('non_conforme', 'Produit non conforme'), ('autre', 'Autre')], max_length=50)),
                ('date_retour', models.DateField(auto_now_add=True)),
                ('livreur', models.CharField(blank=True, max_length=255, null=True)),
                ('informations_supp', models.TextField(blank=True, null=True)),
                ('numero_c', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_retour', models.CharField(default='en attente', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.customer')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.customer')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.salesorder'),
        ),
        migrations.CreateModel(
            name='InvoiceNote',
            fields=[
                ('invoice', models.AutoField(primary_key=True, serialize=False)),
                ('datef', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('addressf', models.CharField(blank=True, max_length=255, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('qte_facture', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qte_delivred', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pc', models.CharField(blank=True, max_length=255, null=True)),
                ('ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('delivery', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_delivered', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('transportation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.salesorder')),
            ],
        ),
    ]
