# Generated by Django 5.1.2 on 2024-10-21 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_type', models.CharField(choices=[('volume', 'Volume customer'), ('retail', 'Retail customer')], default='retail', max_length=10)),
            ],
            options={
                'db_table': 'apps_customer',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('delivery_person', models.CharField(max_length=100)),
                ('delivery_person_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'apps_Delivery',
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('volume_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'apps_item',
            },
        ),
        migrations.CreateModel(
            name='lead',
            fields=[
                ('lead', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=55, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=55, null=True)),
                ('position', models.CharField(blank=True, max_length=55, null=True)),
                ('contact', models.CharField(blank=True, max_length=55, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apps_lead',
            },
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, max_length=35, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=35, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('categories_supplied', models.CharField(blank=True, max_length=45, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=45, null=True)),
                ('product_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('interaction_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apps_supplier',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('apps.customuser',),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('Command_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statu', models.CharField(choices=[('pending', 'Pending'), ('Shipping', 'Shipping'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.customer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='apps.delivery')),
            ],
            options={
                'db_table': 'apps_Command',
            },
        ),
        migrations.CreateModel(
            name='itemvariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('variant_value', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.item')),
            ],
            options={
                'db_table': 'apps_itemvariant',
            },
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('facture_id', models.AutoField(primary_key=True, serialize=False)),
                ('datef', models.DateField(blank=True, null=True)),
                ('addressf', models.CharField(blank=True, max_length=100, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=55, null=True)),
                ('qte_facture', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.command')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.item')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.itemvariant')),
            ],
            options={
                'db_table': 'apps_facture',
            },
        ),
        migrations.CreateModel(
            name='leaddata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=55, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('nextdate', models.DateField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('worker', models.CharField(blank=True, max_length=30, null=True)),
                ('leadsrc', models.CharField(blank=True, max_length=55, null=True)),
                ('sector', models.CharField(blank=True, max_length=55, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('closed', 'Closed')], max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.lead')),
            ],
            options={
                'db_table': 'apps_leaddata',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.item')),
                ('item_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.itemvariant')),
            ],
            options={
                'db_table': 'apps_stock',
            },
        ),
        migrations.CreateModel(
            name='retour',
            fields=[
                ('retour', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_retournee', models.PositiveIntegerField()),
                ('raison_retour', models.TextField(blank=True, null=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('livreur', models.CharField(blank=True, max_length=55, null=True)),
                ('informations_supp', models.TextField(blank=True, null=True)),
                ('statut_retour', models.CharField(default='en attente', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.customer')),
                ('numero_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.command')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.item')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.itemvariant')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.supplier')),
            ],
            options={
                'db_table': 'apps_retour',
            },
        ),
        migrations.CreateModel(
            name='bonreception',
            fields=[
                ('delivery', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_delivered', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('transportation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.item')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.itemvariant')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.supplier')),
            ],
            options={
                'db_table': 'apps_bonreception',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'permission'), name='unique_user_permission')],
            },
        ),
    ]
