# Generated by Django 5.1.1 on 2024-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
