# Generated by Django 5.1.2 on 2024-10-21 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreurs',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number', models.CharField(blank=True, max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'apps_Livreurs',
            },
            bases=('apps.customuser',),
        ),
    ]
