# Generated by Django 5.1.2 on 2024-11-21 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retour',
            name='client',
        ),
        migrations.RemoveField(
            model_name='retour',
            name='numero_c',
        ),
        migrations.RemoveField(
            model_name='retour',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='retour',
            name='quantite_retournee',
        ),
        migrations.RemoveField(
            model_name='retour',
            name='statut_retour',
        ),
        migrations.RemoveField(
            model_name='retour',
            name='variant',
        ),
        migrations.AddField(
            model_name='retour',
            name='facture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.facture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retour',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.supplier'),
        ),
    ]
