# Generated by Django 5.1.2 on 2024-10-23 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_livreurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Delivery',
            name='delivery_person',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='apps.livreurs'),
        ),
        migrations.AlterField(
            model_name='retour',
            name='livreur',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='apps.livreurs'),
        ),
    ]
