# Generated by Django 5.1.1 on 2024-09-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_id_centreddata_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddata',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('closed', 'Closed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicenote',
            name='addressf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicenote',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicenote',
            name='payment_method',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='invoicenote',
            name='pc',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='retour',
            name='livreur',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='retour',
            name='numero_c',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='feedback',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
