# Generated by Django 5.0.1 on 2024-11-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_retour_client_remove_retour_numero_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.stock'),
        ),
    ]
