# Generated by Django 5.1.1 on 2024-09-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_supplier_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier',
            new_name='supplier_id',
        ),
    ]
