# Generated by Django 5.1.1 on 2024-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_supplier_supplier_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retour',
            name='raison_retour',
            field=models.TextField(blank=True, null=True),
        ),
    ]
