# Generated by Django 5.0.1 on 2024-11-24 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_notification_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_person',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='apps.livreurs'),
        ),
    ]
