# Generated by Django 5.1.1 on 2024-09-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_adddata_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adddata',
            table='apps_adddata',
        ),
        migrations.AlterModelTable(
            name='centreddata',
            table='apps_centreddata',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='apps_customer',
        ),
        migrations.AlterModelTable(
            name='deliverynote',
            table='apps_deliverynote',
        ),
        migrations.AlterModelTable(
            name='invoicenote',
            table='apps_invoicenote',
        ),
        migrations.AlterModelTable(
            name='itemvariant',
            table='apps_itemvariant',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='apps_orderitem',
        ),
        migrations.AlterModelTable(
            name='retour',
            table='apps_retour',
        ),
        migrations.AlterModelTable(
            name='salesorder',
            table='apps_salesorder',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='apps_supplier',
        ),
    ]
