# Generated by Django 5.1.1 on 2024-09-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_adddata_table_alter_centreddata_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='order',
            new_name='order_id',
        ),
    ]
