# Generated by Django 5.1.2 on 2024-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customuser', 'CustomUser'), ('admin', 'AdminUser'), ('livreur', 'Livreurs')], default='customuser', max_length=10),
        ),
    ]
