# Generated by Django 5.1.1 on 2024-09-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_retour_raison_retour'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonreception',
            name='variant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.itemvariant'),
        ),
    ]
