# Generated by Django 5.1.2 on 2024-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_delivery_delivery_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
