# Generated by Django 5.1.1 on 2024-09-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_bonreception_variant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonreception',
            old_name='supplier',
            new_name='supplier_id',
        ),
    ]
