# Generated by Django 5.0.1 on 2024-09-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_supplier_bonreception_supplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='facture',
            new_name='facture_id',
        ),
    ]
